# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

EMAlgorithmAll <- function(em_method, probability_method, maximum_iterations, stopping_threshold, verbose) {
    .Call(`_infPackage_EMAlgorithmAll`, em_method, probability_method, maximum_iterations, stopping_threshold, verbose)
}

EMAlgorithmCDF <- function(probability_method, maximum_iterations, stopping_threshold, verbose, multivariate_method, multivariate_epsilon, multivariate_iterations) {
    .Call(`_infPackage_EMAlgorithmCDF`, probability_method, maximum_iterations, stopping_threshold, verbose, multivariate_method, multivariate_epsilon, multivariate_iterations)
}

EMAlgorithmHitAndRun <- function(probability_method, maximum_iterations, stopping_threshold, verbose, step_size, samples) {
    .Call(`_infPackage_EMAlgorithmHitAndRun`, probability_method, maximum_iterations, stopping_threshold, verbose, step_size, samples)
}

RprecomputeHR <- function(samples, step_size) {
    invisible(.Call(`_infPackage_RprecomputeHR`, samples, step_size))
}

RprecomputeExact <- function() {
    invisible(.Call(`_infPackage_RprecomputeExact`))
}

RsetParameters <- function(candidate_matrix, group_matrix) {
    invisible(.Call(`_infPackage_RsetParameters`, candidate_matrix, group_matrix))
}

readFromFile <- function(filename) {
    invisible(.Call(`_infPackage_readFromFile`, filename))
}

