# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

RsetParameters <- function(x, w) {
    invisible(.Call(`_infPackage_RsetParameters`, x, w))
}

readFilePrint <- function(filename, method) {
    invisible(.Call(`_infPackage_readFilePrint`, filename, method))
}

