# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

RsetParameters <- function(candidate_matrix, group_matrix) {
    invisible(.Call(`_fastei_RsetParameters`, candidate_matrix, group_matrix))
}

EMAlgorithmFull <- function(em_method, probability_method, maximum_iterations, maximum_seconds, stopping_threshold, verbose, step_size, samples, monte_method, monte_error, monte_iter) {
    .Call(`_fastei_EMAlgorithmFull`, em_method, probability_method, maximum_iterations, maximum_seconds, stopping_threshold, verbose, step_size, samples, monte_method, monte_error, monte_iter)
}

