// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// RsetParameters
void RsetParameters(Rcpp::NumericMatrix x, Rcpp::NumericMatrix w);
RcppExport SEXP _infPackage_RsetParameters(SEXP xSEXP, SEXP wSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type w(wSEXP);
    RsetParameters(x, w);
    return R_NilValue;
END_RCPP
}
// readFilePrint
void readFilePrint(Rcpp::String filename);
RcppExport SEXP _infPackage_readFilePrint(SEXP filenameSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::String >::type filename(filenameSEXP);
    readFilePrint(filename);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_infPackage_RsetParameters", (DL_FUNC) &_infPackage_RsetParameters, 2},
    {"_infPackage_readFilePrint", (DL_FUNC) &_infPackage_readFilePrint, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_infPackage(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
